// This file was generated by the "generate_version.pl" utility
// You should not modify it manually, as it may be re-generated.
//

#include "Version.hpp"
#include <sstream>

#ifdef PWIZ_USER_VERSION_INFO_H // in case you need to add any info version of your own
#include PWIZ_USER_VERSION_INFO_H  // must define PWIZ_USER_VERSION_INFO_H_STR for use below
#endif

namespace pwiz{
namespace msdata{

int Version::Major()                {return 3;}
int Version::Minor()                {return 0;}
int Version::Revision()             {return 6002
;}
std::string Version::LastModified() {return "0-0-0 (unknown revision)";}
std::string Version::str()
{
       std::ostringstream v;
       v << Major() << '.' << Minor() << '.' << Revision();
#ifdef PWIZ_USER_VERSION_INFO_H
       v << " (" << PWIZ_USER_VERSION_INFO_H_STR << ")";
#endif
       return v.str();
}

} // namespace msdata
} // namespace pwiz
;
