all:
	cd base; make
	cd spec; make
	cd prsm; make
	cd zeroptmsearch; make
	cd tdgf; make
	cd filterdiagonal; make
	cd ptmsearch; make

clean:
	cd base; make clean
	cd spec; make clean
	cd prsm; make clean
	cd zeroptmsearch; make clean
	cd tdgf; make clean
	cd filterdiagonal; make clean
	cd ptmsearch; make clean
